run:
  concurrency: 4
  tests: true  # 是否检查 _test.go 文件
  linters:
    enable:
      - govet
      - errcheck
      - staticcheck
      - gofmt
      - goimports
      - deadcode
      - unused
      - ineffassign
      - typecheck
      - varcheck
    disable:
      - scopelint

linters-settings:
  gofmt:
    simplify: true

issues:
  severity:
    - error
  max-issues-per-linter: 100
  max-same-issues: 3
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck 
  include-rules: []

output:
  formats: colored-line-number  # 输出格式，可以是 text, json, line-number, etc.
  sort-results: true
  print-issued-lines: true
