development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=develop user=postgres password=postgres sslmode=disable
  dir: migrations/postgres

production:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=develop user=postgres password=postgres sslmode=require
  dir: migrations/postgres
