services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'develop'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always

  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    user: root
    # restart: always
    # container_name: rocketmq-broker
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      # 采用下面的方式则使用 docker volume，需要在下方配置数据卷
      - rocketmq_broker_logs:/home/rocketmq/logs
      - rocketmq_broker_data:/home/rocketmq/store
      - ./conf/broker.conf:/home/rocketmq-5.3.1/conf/broker.conf
      # - ./conf:/home/rocketmq-5.3.1/conf
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      # - JAVA_OPTS:=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms64m -Xmx64m -Xmn64m
    depends_on:
      - rocketmq-namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    # 这里需要事先配置 ./conf/broker.conf 文件
    command: sh mqbroker -c /home/rocketmq-5.3.1/conf/broker.conf

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    restart: always
    # container_name: rocketmq-namesrv
      # environment:
      #   JAVA_OPT_EXT: "-server -Xms64m -Xmx64m -Xmn64m"
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      - rocketmq_namesrv_logs:/home/rocketmq/logs
    ports:
      - 9876:9876
    command: sh mqnamesrv
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    restart: always
    # container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.config.namesrvAddr=rocketmq-namesrv:9876 -Dserver.port=8180 -Drocketmq.config.isVIPChannel=false
      # - JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m
    depends_on:
      - rocketmq-namesrv
    ports:
      - 8180:8180

# 配置数据卷
volumes:
  rocketmq_namesrv_logs:
    name: rocketmq_namesrv_logs
    external: true
  rocketmq_broker_data:
    name: rocketmq_broker_data
    external: true 
  rocketmq_broker_logs:
    name: rocketmq_broker_logs
    external: true
  db_data:
    name: "db_data"
    external: true
